[package]
name = "libcrux"
version = "0.0.1"
edition = "2021"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
license = "Apache2.0"


[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
libcrux-hacl = { path = "sys/hacl" }
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.4"
