[package]
name = "libcrux"
version = "0.0.1"
edition = "2021"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
license = "Apache2.0"


[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
hacspec-lib = { git = "https://github.com/hacspec/hacspec" }
libcrux-hacl = { path = "sys/hacl" }
au_curves = { path = "au_curves" }
log = "0.4"

[target.'cfg(any(target_arch = "x86_64", target_arch = "x86"))'.dependencies]
libjade = { path = "sys/libjade" }

[dev-dependencies]
pretty_env_logger = "0.4"
rand = { version = "0.8" }
rand_core = { version = "0.6" }
criterion = "0.3"

[[bench]]
name = "criterion_benchmarks"
harness = false
