[package]
name = "libjade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[build-dependencies]
libc = { version = "0.2", default-features = false }
fs_extra = "1.2"

[target.'cfg(not(windows))'.build-dependencies]
bindgen = "0.63"

[dev-dependencies]
pretty_env_logger = "0.4"
