[package]
name = "libjade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
libjade_sha256 = { path = "sha256"}
libjade_x25519 = { path = "x25519"}

[dev-dependencies]
pretty_env_logger = "0.4"
