name: Checks

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🧹 Cargo fmt
        run: cargo fmt --all -- --check

  mq_status:
    if: |
      always() &&
      github.event_name ==  'workflow_dispatch' || github.event_name ==  'merge_group'
    needs: [fmt]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
