name: ML-KEM

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:
  merge_group:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          - bits: 32
            os: "macos-latest"
          # FIXME: Linking isn't working here yet for hacl #42
          - bits: 32
            os: "windows-latest"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: libcrux-ml-kem

    steps:
      - uses: actions/checkout@v4

      - run: echo "RUST_TARGET_FLAG=" > $GITHUB_ENV
        if: ${{ matrix.bits == 64 }}
      
      - name: 🛠️ Setup Rust Nightly
        run: rustup toolchain install nightly

      - name: 🛠️ Setup Ubuntu x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add i686-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: 🛠️ Setup Ubuntu x64
        if: ${{ matrix.bits == 64 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add aarch64-unknown-linux-gnu

      # Set up 32 bit systems

      - name: 🛠️ Config Windows x86
        run: echo "RUST_TARGET_FLAG=--target=i686-pc-windows-msvc" > $GITHUB_ENV
        if: ${{ matrix.bits == 32 && matrix.os == 'windows-latest' }}

      - name: 🛠️ Config Linux x86
        run: |
          echo "RUST_TARGET_FLAG=--target=i686-unknown-linux-gnu" > $GITHUB_ENV
        if: ${{ matrix.bits == 32 && matrix.os == 'ubuntu-latest' }}

      # Set up windows

      - name: 🛠️ Setup Windows x86
        if: ${{ matrix.bits == 32 && matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x86-windows-static-md

      - name: 🛠️ Setup Windows x64
        if: ${{ matrix.bits == 64 && matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md

      # Build ...

      - name: 🔨 Build
        run: cargo build --verbose $RUST_TARGET_FLAG

      - name: 🔨 Build Release
        run: cargo build --verbose --release $RUST_TARGET_FLAG

      - name: 🏃🏻 Asan MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: RUSTDOCFLAGS=-Zsanitizer=address RUSTFLAGS=-Zsanitizer=address cargo +nightly test --release --target aarch64-apple-darwin

      - name: 🏃🏻 Asan Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: RUSTDOCFLAGS=-Zsanitizer=address RUSTFLAGS=-Zsanitizer=address cargo +nightly test --release --target x86_64-unknown-linux-gnu

      # Test ...

      - name: 🏃🏻‍♀️ Test
        run: cargo test --verbose $RUST_TARGET_FLAG

      - name: 🏃🏻‍♀️ Test Release
        run: cargo test --verbose --release $RUST_TARGET_FLAG

  benchmarks:
    strategy:
      fail-fast: true
      matrix:
        bits: [32, 64]
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          # There's no such thing as 32-bit macOS
          - bits: 32
            os: "macos-latest"
          # FIXME: Linking isn't working here yet for hacl #42
          - bits: 32
            os: "windows-latest"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: libcrux-ml-kem

    steps:
      - uses: actions/checkout@v4

      - run: echo "RUST_TARGET_FLAG=" > $GITHUB_ENV
        if: ${{ matrix.bits == 64 }}

      - name: 🛠️ Setup Ubuntu x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add i686-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: 🛠️ Setup Ubuntu x64
        if: ${{ matrix.bits == 64 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add aarch64-unknown-linux-gnu

      - name: 🛠️ Setup macOS
        if: ${{  matrix.os == 'macos-latest' }}
        run: |
          rustup target add aarch64-apple-darwin

      # Set up 32 bit systems

      - name: 🛠️ Config Windows x86
        run: echo "RUST_TARGET_FLAG=--target=i686-pc-windows-msvc" > $GITHUB_ENV
        if: ${{ matrix.bits == 32 && matrix.os == 'windows-latest' }}

      - name: 🛠️ Config Linux x86
        run: |
          echo "RUST_TARGET_FLAG=--target=i686-unknown-linux-gnu" > $GITHUB_ENV
        if: ${{ matrix.bits == 32 && matrix.os == 'ubuntu-latest' }}

      # Set up windows

      - name: 🛠️ Setup Windows x86
        if: ${{ matrix.bits == 32 && matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x86-windows-static-md

      - name: 🛠️ Setup Windows x64
        if: ${{ matrix.bits == 64 && matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md

      # Benchmarks ...

      - name: 🏃🏻‍♀️ Benchmarks Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: cargo bench --verbose $RUST_TARGET_FLAG

      - name: 🏃🏻‍♀️ Benchmarks Clang
        if: ${{ matrix.os != 'windows-latest' }}
        run: CC=clang cargo bench --verbose $RUST_TARGET_FLAG

  platform:
    strategy:
      fail-fast: false
      matrix:
        bits: [32, 64]
        os:
          - macos-13 # Intel mac
          - macos-latest # macos-14 m1
          - ubuntu-latest
          - windows-latest
        exclude:
          - bits: 32
            os: "macos-latest"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: sys/platform

    steps:
      - uses: actions/checkout@v4

      - name: 🔨 Build
        run: cargo build --verbose

      - name: 🏃🏻‍♀️ Test
        run: cargo test --verbose -- --nocapture

      - name: 🏃🏻‍♀️ Test Release
        run: cargo test --verbose --release -- --nocapture

      - name: 🛠️ Setup Linux x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: |
          rustup target add i686-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: 🏃🏻‍♀️ Test Linux x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: cargo test --verbose --target i686-unknown-linux-gnu -- --nocapture

      - name: 🏃🏻‍♀️ Test Release Linux x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'ubuntu-latest' }}
        run: cargo test --verbose --release --target i686-unknown-linux-gnu -- --nocapture

      - name: 🏃🏻‍♀️ Test Windows x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'windows-latest' }}
        run: cargo test --verbose --target i686-pc-windows-msvc -- --nocapture

      - name: 🏃🏻‍♀️ Test Release Windows x86
        if: ${{ matrix.bits == 32 &&  matrix.os == 'windows-latest' }}
        run: cargo test --verbose --release --target i686-pc-windows-msvc -- --nocapture
