name: Nix

on:
  push:
    branches: [main, dev]
  pull_request:
  merge_group:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Install & configure Cachix
        shell: bash
        run: |
          nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
          cachix use hax
      - uses: actions/checkout@v4
      - run: nix build -L .#ml-kem

  mq_status:
    if: |
      always() &&
      github.event_name ==  'workflow_dispatch' || github.event_name ==  'merge_group'
    needs: [nix]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
