name: Specs

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    
    - name: Setup Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install ninja-build
    - name: Setup MacOS
      if: matrix.os == 'macos-latest'
      run: brew install ninja
    - name: Setup Windows
      if: matrix.os == 'windows-latest'
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        vcpkg install openssl:x64-windows-static-md

    - uses: actions/checkout@v3

    - name: Update dependencies
      run: cargo update

    - name: Build
      working-directory: specs
      run: cargo build --verbose

    - name: Run tests
      working-directory: specs
      run: cargo test --verbose

mq_status:
    if: |
      always() &&
      github.event_name ==  'workflow_dispatch' || github.event_name ==  'merge_group'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
